export { default as SideBar } from './SideBar/SideBar';
export { default as ProfileManager } from './ProfileManager/ProfileManager';
export { default as AddProduct } from './AddProduct/AddProduct';
export { default as Home } from './Home/Home'
export { default as EditProduct } from './EditProduct/EditProduct';
export { default as EditProductDetails } from './EditProduct/EditProductDetails/EditProductDetails';
export { default as Orders } from './Orders/Orders';
export { default as Sales } from './Sales/Sales';
export { default as Payout } from './Payout/Payout';
export { default as StoreManagement } from './StoreManagement/StoreManagement';
export { default as SubscriptionView } from './SubscriptionView/SubscriptionView';